name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Git pull
      uses: actions/checkout@v1
      
    - name: Setup python
      uses: actions/setup-python@v1 
      with:
        python-version: '3.x'
        architecture: 'x64' 
    
    - name: Setup openstack client
      run: |
        pip install wheel
        pip install python-openstackclient
        pip install python-magnumclient
        
    - name: Get k8s context
      run: |
        $(openstack coe cluster config ${{ secrets.CLUSTER_NAME }} --os-auth-url ${{ secrets.URL }} --os-identity-api-version 3 --os-project-name ${{ secrets.PROJECT_NAME }} --os-project-domain-name ${{ secrets.USER_DOMAIN_NAME }} --os-username ${{ secrets.USERNAME }} --os-user-domain-name ${{ secrets.USER_DOMAIN_NAME }} --os-password ${{ secrets.PASSWORD }}) &

    - name: Setup kubectl
      run: |
       sudo apt-get update && sudo apt-get install -y apt-transport-https
       curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
       echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
       sudo apt-get update
       sudo apt-get install -y kubectl
       
    - name: Set k8s context and Get cluster-info
      run: |
       export KUBECONFIG=./config
       kubectl cluster-info
       
    - name: Build the Docker image        
      run: | 
       sha=${GITHUB_SHA:0:7}
       app="${GITHUB_REPOSITORY#*/}"
       docker build --file Dockerfile -t docker.pkg.github.com/$GITHUB_REPOSITORY/$app:$sha .
       
   - name: Push Docker image to Docker Registry ## use token (not password) for Github Package Registry
     run: |
       sha=${GITHUB_SHA:0:7}
       app="${GITHUB_REPOSITORY#*/}"
       docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
       docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$app:$sha
